project:
  type: book
  output-dir: docs

book:
  title: BOEM Report
  subtitle: Report prepared by NOAA Northeast Fisheries Science Center 
  date: 
  downloads: [pdf, docx]
  author:
  - name: 
    affiliations:
      - id: 
        name: 
        department: 
        address: 
         
  - name: 
    affiliations:
      - ref: 
  - name: Sofie M. Van Parijs
    affiliations:
      - ref: nefsc-psd

  chapters:
    - index.qmd
    - Chapter1.qmd
    - Results.qmd
    - Discussion.qmd
    - references.qmd

  site-url: https://nmfs-opensci.github.io/NOAA-tech-memo-template/
  repo-url: https://github.com/Isabellagarf/Report_Example
  repo-actions: [edit, source, issue]
  search: true

bibliography: 
  - references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    cite-method: biblatex

metadata-files:
  - _frontmatter.yml
  
